---
title: "The Attractiveness of Cities"
subtitle: "Project 2"
author: "James Aas, Audrey Mills, Jameson Oates"
format: html
editor: visual
execute:
  echo: false
  warning: false
  message: false
---

## Data Wrangling

```{r load-packages}
#| label: load-pkgs
#| message: false
#| warning: false

library(tidyverse)
library(dplyr)
library(tidyr)
library(leaflet)
library(tmap)
library(readr)
library(leaflet)
library(maps)
library(gganimate)
```

```{r load-data}
#| label: load-data
#| message: false

state_economic_data <- read.csv("data/state_economic_data.csv")

state_abortion_data <- read.csv("data/abortions_dataset.csv")

state_immigration_data <- read.csv("data/interstate_migration_data.csv")

state <- c("Alabama", 
           "Alaska", 
           "Arizona", 
           "Arkansas",
           "California",
           "Colorado",
           "Connecticut",
           "Delaware",
           "District of Columbia",
           "Florida",
           "Georgia",
           "Hawaii",
           "Idaho",
           "Illinois",
           "Indiana",
           "Iowa",
           "Kansas",
           "Kentucky",
           "Louisiana",
           "Maine",
           "Maryland",
           "Massachusetts",
           "Michigan", 
           "Minnesota",
           "Mississippi",
           "Missouri",
           "Montana",
           "Nebraska",
           "Nevada",
           "New Hampshire",
           "New Jersey",
           "New Mexico",
           "New York",
           "North Carolina",
           "North Dakota",
           "Ohio",
           "Oklahoma",
           "Oregon",
           "Pennsylvania",
           "Rhode Island",
           "South Carolina",
           "South Dakota",
           "Tennessee",
           "Texas",
           "Utah",
           "Vermont",
           "Virginia",
           "Washington",
           "West Virginia",
           "Wisconsin", 
           "Wyoming")

political_culture <- c("Traditionalistic", 
                       "Individualistic", 
                       "Traditionalistic", 
                       "Traditionalistic", 
                       "Moralistic", 
                       "Moralistic", 
                       "Individualistic",
                       "Individualistic", 
                       "Individualistic", 
                       "Traditionalistic",
                       "Traditionalistic", 
                       "Individualistic", 
                       "Moralistic", 
                       "Individualistic", 
                       "Individualistic", 
                       "Moralistic", 
                       "Moralistic", 
                       "Traditionalistic", 
                       "Traditionalistic", 
                       "Moralistic", 
                       "Individualistic", 
                       "Individualistic", 
                       "Moralistic", 
                       "Moralistic", 
                       "Traditionalistic",
                       "Individualistic",
                       "Moralistic",
                       "Individualistic",
                       "Individualistic",
                       "Moralistic",
                       "Individualistic",
                       "Traditionalistic",
                       "Individualistic",
                       "Traditionalistic",
                       "Moralistic",
                       "Individualistic",
                       "Traditionalistic",
                       "Moralistic",
                       "Individualistic",
                       "Individualistic",
                       "Traditionalistic",
                       "Moralistic", 
                       "Traditionalistic",
                       "Traditionalistic",
                       "Moralistic", 
                       "Moralistic", 
                       "Traditionalistic", 
                       "Moralistic", 
                       "Traditionalistic",
                       "Moralistic", 
                       "Individualistic")

political_culture_elazar <- data.frame(state, political_culture) %>%
  mutate(state = tolower(state))

head(presidential_election_data)
```

```{r}
state_abortion_data <- state_abortion_data %>%
  slice(-(1:1)) %>%
  rename(
    Area = 1,
    Number = 2,
    Rate = 3,
    Ratio = 4,
    `Out-of-State (number and percentage)` = 5,
    Year = 6
  ) %>%
  mutate(
    Number = ifelse(Number %in% c("N/A"), NA, Number),
    Rate = ifelse(Rate %in% c("N/A"), NA, Rate),
    Ratio = ifelse(Ratio %in% c("N/A"), NA, Ratio),
    `Out-of-State (number and percentage)` = ifelse(`Out-of-State (number and percentage)` %in% c("N/A"), NA, `Out-of-State (number and percentage)`)
  )  %>%
  filter(!(Number %in% c("25,619", 
                         "30,555", 
                         "35,398", 
                         "37,523", 
                         "73,815", 
                         "89,469", 
                         "59,854", 
                         "27,471"))) %>%
  mutate(Number = as.numeric(gsub(",", "", Number)), 
         Rate = as.numeric(gsub(",", "", Rate)),
         Ratio = as.numeric(gsub(",", "", Ratio)),
         Year = as.numeric(gsub(",", "", Year))
         ) %>%
  mutate(Area = tolower(Area))
head(state_abortion_data)
```

```{r}
state_immigration_data <- state_immigration_data %>%
   slice(-(1:6)) %>%
  rename(
    `Current residence in`  = 1,
    `Population 1 year and over: Estimate` = 2,
    `Population 1 year and over: MOE` = 3,
    `Same house 1 year ago: Estimate` = 4,
    `Same house 1 year ago: MOE` = 5,
    `Same state of residence 1 year ago: Estimate` = 6,
    `Same state of residence 1 year ago: MOE` = 7,
    `Different state of residence 1 year ago: Estimate` = 8,
    `Different state of residence 1 year ago: MOE` = 9,
    Year = 10
  ) %>%
  slice(-(1:6)) %>%
  mutate(
    `Population 1 year and over: Estimate` = as.numeric(
      gsub(",", "", `Population 1 year and over: Estimate`)
      ),
    `Same house 1 year ago: Estimate` = as.numeric(
      gsub(",", "", `Same house 1 year ago: Estimate`)
      ), 
    `Same state of residence 1 year ago: Estimate` = as.numeric(
      gsub(",", "", `Same state of residence 1 year ago: Estimate`)
      ), 
    `Different state of residence 1 year ago: Estimate` = as.numeric(
      gsub(",", "", `Different state of residence 1 year ago: Estimate`)
      )
          
    ) 
head(state_immigration_data)
```

```{r}
state_economic_data <- state_economic_data %>%
  rename(
    State  = 1,
    `Median Household Income` = 2,
    Year = 3
  ) %>%
  mutate(
    State = ifelse(State == "", NA, State),
    `Median Household Income` = ifelse(`Median Household Income` == "", NA, `Median Household Income`)
    ) %>%
  filter(complete.cases(.)) %>%
  mutate(`Median Household Income` = as.numeric(gsub(",", "", `Median Household Income`))) %>%
  mutate(State = tolower(State))
head(state_economic_data)
```

```{r}
presidential_election_data <- read.csv("data/presidential_election_data.csv")

presidential_election_data <- presidential_election_data %>%
  subset(select = -c(X1, X, TOTAL.VOTES, TOTAL.VOTES..)) %>%
  mutate(
    FEC.ID = ifelse(FEC.ID == "n/a", NA, FEC.ID)
  ) %>%
  mutate(`GENERAL.RESULTS` = as.numeric(gsub(",", "", `GENERAL.RESULTS`))) %>%
  mutate(STATE = tolower(STATE)) %>%
  filter(PARTY == "R") %>%
  mutate("R Share of General" = GENERAL.. ) %>%
  select(STATE, 'R Share of General', YEAR) 

```

```{r}
abortion_and_economic <- full_join(state_abortion_data, 
             state_economic_data,
             by = c("Area" = "State",
                    "Year" = "Year"))
abortion_and_economic <- abortion_and_economic %>%
  mutate(Year = as.numeric(gsub(",", "", Year)))

state_immigration_data <- state_immigration_data %>%
  mutate(Year = as.numeric(gsub(",", "", Year))) 

culture_president <- left_join(presidential_election_data, 
                               political_culture_elazar,
                                 by = c("STATE"= "state")) 
everything_but_immigration <- left_join(culture_president, 
                               abortion_and_economic,
                    by = c("STATE" = "Area",
                    "YEAR" = "Year"))

all_variables_dataset<- full_join(everything_but_immigration, 
            state_immigration_data,
            by = c("STATE" = "Current residence in",
                   "YEAR" = "Year"))
  
head(all_variables_dataset)
```

```{r}
library(usmap)
statepov <- statepov
countypov <- countypov
statep <- countypov %>% group_by(abbr) %>%
summarize(avgpov = mean(pct_pov_2021))
statep <- statep %>% 
  rename(
    state = abbr)


plot_usmap(data = statepov, values = "pct_pov_2021", include = c(), color = "blue") + scale_fill_continuous(low = "white", high = "blue", name = "Poverty Percentage Estimates", label = scales::comma) + labs(title = "hurah", subtitle = "using the internets dataset") + theme(legend.position = "right")

plot_usmap(data = statep, values = "avgpov", include = c(), color = "blue") + scale_fill_continuous(low = "white", high = "blue", name = "Poverty Percentage Estimates", label = scales::comma) + labs(title = "hurah", subtitle = "using my dataset (that came from the internet dataset") + theme(legend.position = "right")


```

```{r}
econ_data <- state_economic_data

econ_map_data <- map_data("state")

econ_merged_data <- merge(econ_map_data, econ_data, by.x = "region", by.y = "State", all.x = TRUE)

econ_animate <- ggplot(econ_merged_data, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = `Median Household Income`)) +
  scale_fill_gradient(name = "Median Household Income", low = "lightblue", high = "darkblue", na.value = "grey", guide = "legend") +
  theme_void() +
  labs(subtitle = "Real Median Household Income over Time", caption = "Source: FRED") +
  transition_states(Year) +
  labs(title = "Year: {closest_state}") + 
  theme(plot.title = element_text(hjust = 0.5))  

animate(econ_animate, renderer = gifski_renderer())
```

```{r}
abortion_data <- state_abortion_data

abortion_map_data <- map_data("state")

abortion_merged_data <- merge(abortion_map_data, abortion_data, by.x = "region", by.y = "Area", all.x = TRUE)

abortion_animate <- ggplot(abortion_merged_data, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = Number)) +
  scale_fill_gradient(name = "Abortions", low = "pink", high = "darkred", na.value = "grey", guide = "legend") +
  theme_void() +
  labs(subtitle = "Abortions by State Residents over Time", caption = "Source: CDC") +
  transition_states(Year) +
  labs(title = "Year: {closest_state}") + 
  theme(plot.title = element_text(hjust = 0.5))  

animate(abortion_animate, renderer = gifski_renderer())
```

```{r}
political_data <- political_culture_elazar

political_map_data <- map_data("state")

political_merged_data <- merge(political_map_data, political_data, by.x = "region", by.y = "state", all.x = TRUE)

political_map <- ggplot(political_merged_data, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = political_culture), color = "black", size = 0.2) +
  scale_fill_manual(values = c("lightgreen", "magenta", "lightyellow"), name = "") +
  theme_void() +
  labs(subtitle = "Elazar's Cultural Classification by State", caption = "Source: Daniel Elazar")  
political_map
```

**ABSTRACT**

**INTRODUCTION**

**LINEAR MODEL**

```{r}
library(moderndive)
immigration_mlr <-lm(`Different state of residence 1 year ago: Estimate` ~ `Median Household Income` + 
                      `political_culture` + 
                       Number+ 
                       `R Share of General`, 
                     data = all_variables_dataset)
get_regression_table(immigration_mlr)
```

"The best way to visualize multiple linear regression is to **create a visualization for each independent variable while holding the other independent variables constant**."

```{r}
library(ggplot2)
ggplot(data = all_variables_dataset, aes(x = "Different state of residence 1 year ago: Estimate", y ="Median Household Income", color = political_culture))+
geom_point()+
  geom_smooth(method = "lm", se=F)
```
