---
title: "The Attractiveness of Cities"
subtitle: "Project 2"
author: "Jameson Oates, James Aas, Audrey Mills"
title-slide-attributes:
  data-slide-number: none
format: revealjs
editor: visual
execute:
  echo: false
---

```{r}
#| label: load-packages
#| include: false

library(tidyverse)
library(tidyverse)
library(dplyr)
library(tidyr)
library(leaflet)
library(tmap)
library(readr)
library(leaflet)
library(maps)
library(gganimate)
library(moderndive)
library(ggplot2)
```

```{r}
#| label: setup
#| include: false

# For better figure resolution
knitr::opts_chunk$set(
  fig.retina = 3, 
  dpi = 300, 
  fig.width = 6, 
  fig.asp = 0.618, 
  out.width = "70%"
  )
```

```{r}
#| label: load-data
#| include: false
#| 
```

------------------------------------------------------------------------

```{r, echo = FALSE}
state_economic_data <- read.csv("data/state_economic_data.csv")

state_abortion_data <- read.csv("data/abortions_dataset.csv")

state_immigration_data <- read.csv("data/interstate_migration_data.csv")

state <- c("Alabama", 
           "Alaska", 
           "Arizona", 
           "Arkansas",
           "California",
           "Colorado",
           "Connecticut",
           "Delaware",
           "District of Columbia",
           "Florida",
           "Georgia",
           "Hawaii",
           "Idaho",
           "Illinois",
           "Indiana",
           "Iowa",
           "Kansas",
           "Kentucky",
           "Louisiana",
           "Maine",
           "Maryland",
           "Massachusetts",
           "Michigan", 
           "Minnesota",
           "Mississippi",
           "Missouri",
           "Montana",
           "Nebraska",
           "Nevada",
           "New Hampshire",
           "New Jersey",
           "New Mexico",
           "New York",
           "North Carolina",
           "North Dakota",
           "Ohio",
           "Oklahoma",
           "Oregon",
           "Pennsylvania",
           "Rhode Island",
           "South Carolina",
           "South Dakota",
           "Tennessee",
           "Texas",
           "Utah",
           "Vermont",
           "Virginia",
           "Washington",
           "West Virginia",
           "Wisconsin", 
           "Wyoming")

political_culture <- c("Traditionalistic", 
                       "Individualistic", 
                       "Traditionalistic", 
                       "Traditionalistic", 
                       "Moralistic", 
                       "Moralistic", 
                       "Individualistic",
                       "Individualistic", 
                       "Individualistic", 
                       "Traditionalistic",
                       "Traditionalistic", 
                       "Individualistic", 
                       "Moralistic", 
                       "Individualistic", 
                       "Individualistic", 
                       "Moralistic", 
                       "Moralistic", 
                       "Traditionalistic", 
                       "Traditionalistic", 
                       "Moralistic", 
                       "Individualistic", 
                       "Individualistic", 
                       "Moralistic", 
                       "Moralistic", 
                       "Traditionalistic",
                       "Individualistic",
                       "Moralistic",
                       "Individualistic",
                       "Individualistic",
                       "Moralistic",
                       "Individualistic",
                       "Traditionalistic",
                       "Individualistic",
                       "Traditionalistic",
                       "Moralistic",
                       "Individualistic",
                       "Traditionalistic",
                       "Moralistic",
                       "Individualistic",
                       "Individualistic",
                       "Traditionalistic",
                       "Moralistic", 
                       "Traditionalistic",
                       "Traditionalistic",
                       "Moralistic", 
                       "Moralistic", 
                       "Traditionalistic", 
                       "Moralistic", 
                       "Traditionalistic",
                       "Moralistic", 
                       "Individualistic")

political_culture_elazar <- data.frame(state, political_culture) %>%
  mutate(state = tolower(state))

state_abortion_data <- state_abortion_data %>%
  slice(-(1:1)) %>%
  rename(
	Area = 1,
	Number = 2,
	Rate = 3,
	Ratio = 4,
	`Out-of-State (number and percentage)` = 5,
	Year = 6
  ) %>%
  mutate(
	Number = ifelse(Number %in% c("N/A"), NA, Number),
	Rate = ifelse(Rate %in% c("N/A"), NA, Rate),
	Ratio = ifelse(Ratio %in% c("N/A"), NA, Ratio),
	`Out-of-State (number and percentage)` = ifelse(`Out-of-State (number and percentage)` %in% c("N/A"), NA, `Out-of-State (number and percentage)`)
  )  %>%
  filter(!(Number %in% c("25,619",
                     	"30,555",
                     	"35,398",
                     	"37,523",
                     	"73,815",
                     	"89,469",
                     	"59,854",
                     	"27,471"))) %>%
  mutate(Number = as.numeric(gsub(",", "", Number)),
     	Rate = as.numeric(gsub(",", "", Rate)),
     	Ratio = as.numeric(gsub(",", "", Ratio)),
     	Year = as.numeric(gsub(",", "", Year))
     	) %>%
  mutate(Area = tolower(Area)) %>%
  mutate(Abortions_per_1000_women = Rate) %>%
  mutate(Abortions_per_1000_live_births = Ratio) %>%
  mutate(`Out_of_state_abortions(number and percentage)` = `Out-of-State (number and percentage)`) %>%
  select(Area, Abortions_per_1000_women, Abortions_per_1000_live_births, Year, `Out_of_state_abortions(number and percentage)`)



state_immigration_data <- state_immigration_data %>%
   slice(-(1:6)) %>%
  rename(
    `Current residence in`  = 1,
    `Population 1 year and over: Estimate` = 2,
    `Population 1 year and over: MOE` = 3,
    `Same house 1 year ago: Estimate` = 4,
    `Same house 1 year ago: MOE` = 5,
    `Same state of residence 1 year ago: Estimate` = 6,
    `Same state of residence 1 year ago: MOE` = 7,
    `Different state of residence 1 year ago: Estimate` = 8,
    `Different state of residence 1 year ago: MOE` = 9,
    Year = 10
  ) %>%
  slice(-(1:6)) %>%
  mutate(
    `Population 1 year and over: Estimate` = as.numeric(
      gsub(",", "", `Population 1 year and over: Estimate`)
      ),
    `Same house 1 year ago: Estimate` = as.numeric(
      gsub(",", "", `Same house 1 year ago: Estimate`)
      ), 
    `Same state of residence 1 year ago: Estimate` = as.numeric(
      gsub(",", "", `Same state of residence 1 year ago: Estimate`)
      ), 
    `Different state of residence 1 year ago: Estimate` = as.numeric(
      gsub(",", "", `Different state of residence 1 year ago: Estimate`)
      )
    ) 
state_economic_data <- state_economic_data %>%
  rename(
    State  = 1,
    `Median Household Income` = 2,
    Year = 3
  ) %>%
  mutate(
    State = ifelse(State == "", NA, State),
    `Median Household Income` = ifelse(`Median Household Income` == "", NA, `Median Household Income`)
    ) %>%
  filter(complete.cases(.)) %>%
  mutate(`Median Household Income` = as.numeric(gsub(",", "", `Median Household Income`))) %>%
  mutate(State = tolower(State))
presidential_election_data <- read.csv("data/presidential_election_data.csv")

presidential_election_data <- presidential_election_data %>%
  subset(select = -c(X1, X, TOTAL.VOTES, TOTAL.VOTES..)) %>%
  mutate(
    FEC.ID = ifelse(FEC.ID == "n/a", NA, FEC.ID),
    `GENERAL.RESULTS` = as.numeric(gsub(",", "", `GENERAL.RESULTS`)),
    STATE = tolower(STATE),
    `R Share of General` = as.numeric(gsub("%", "", `GENERAL..`)) / 100
  ) %>%
  filter(PARTY == "R") %>%
  select(STATE, `R Share of General`, YEAR)

str(presidential_election_data)

abortion_and_economic <- full_join(state_abortion_data, 
             state_economic_data,
             by = c("Area" = "State",
                    "Year" = "Year"))
abortion_and_economic <- abortion_and_economic %>%
  mutate(Year = as.numeric(gsub(",", "", Year)))

state_immigration_data <- state_immigration_data %>%
  mutate(Year = as.numeric(gsub(",", "", Year))) 

culture_president <- left_join(presidential_election_data, 
                               political_culture_elazar,
                                 by = c("STATE"= "state")) 
everything_but_immigration <- left_join(culture_president, 
                               abortion_and_economic,
                    by = c("STATE" = "Area",
                    "YEAR" = "Year"))

all_variables_dataset<- full_join(everything_but_immigration, 
            state_immigration_data,
            by = c("STATE" = "Current residence in",
                   "YEAR" = "Year"))


```

------------------------------------------------------------------------

## Question

How is interstate migration affected by state abortion policy, economic status, political culture, and presidential vote?

------------------------------------------------------------------------

## Goals:

-   Examine the numbers of people moving between states and compare them to potential explaining factors such as:

    -   Access to abortion

    -   Median household income

    -   Elazar's cultural classification

    -   Partisanship

-   Create a spacial-temporal visualization of each of these factors from 2012-2020 as well as a linear model examining state migration as a function of them

------------------------------------------------------------------------

## Datasets

::: panel-tabset
## Abortion

```{r}
head(state_abortion_data, 10)
```

-   Abortions per 1000 women

## Economic

```{r}
head(state_economic_data, 10)
```

## Culture

```{r}
head(political_culture_elazar, 10)
```

## Partisanship

```{r}
head(presidential_election_data, 10)
```

-   \% Republican vote

## Migration

```{r}
head(state_immigration_data, 10)
```
:::

------------------------------------------------------------------------

## Visualizations

------------------------------------------------------------------------

## Linear Model

------------------------------------------------------------------------

## Future Plans

------------------------------------------------------------------------
