<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="James Aas, Audrey Mills, Jameson Oates">

<title>The Attractiveness of Cities - Why Move? Finding State Attractiveness</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">The Attractiveness of Cities</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" rel="" target="" aria-current="page">
 <span class="menu-text">Project</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html" rel="" target="">
 <span class="menu-text">Proposal</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.html" rel="" target="">
 <span class="menu-text">Presentation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/math241s24/project-02-t1w/tree/main" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#questions" id="toc-questions" class="nav-link active" data-scroll-target="#questions"><strong>QUESTIONS</strong></a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><strong>INTRODUCTION</strong></a></li>
  <li><a href="#visualizations" id="toc-visualizations" class="nav-link" data-scroll-target="#visualizations"><strong>VISUALIZATIONS</strong></a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><strong>METHODS</strong></a></li>
  <li><a href="#interpretation-of-models" id="toc-interpretation-of-models" class="nav-link" data-scroll-target="#interpretation-of-models"><strong>INTERPRETATION OF MODELS</strong></a></li>
  <li><a href="#interactive-dashboard" id="toc-interactive-dashboard" class="nav-link" data-scroll-target="#interactive-dashboard"><strong>INTERACTIVE DASHBOARD</strong></a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><strong>CONCLUSION</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Why Move? Finding State Attractiveness</h1>
<p class="subtitle lead">Project 2</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>James Aas, Audrey Mills, Jameson Oates </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="questions" class="level2">
<h2 class="anchored" data-anchor-id="questions"><strong>QUESTIONS</strong></h2>
<p>This project set out to answer the question “How is interstate migration affected by different socio-economic factors such as state abortion policy, economic status, political culture, and presidential vote?</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction"><strong>INTRODUCTION</strong></h2>
<p>The variables examined here are state abortion policy, economic status, political culture, and presidential vote in select years.</p>
<p>The dataset “state_immigration_data,” from the US Census, describes the population estimates and margin of errors of populations, per state and year, of people living in the state one year ago, living in the state in the same house one year ago, living in a different state one year ago, and total population. Recorded are the years 2012, 2016, and 2020. This dataset lets us track the population levels of each state over time, based on who lived where one year before being recorded.</p>
<p>The dataset “state_abortion_data,” from the CDC, contains information on the number of abortions per 1000 women in each state in the years 2008, 2012, 2016, and 2020. It also includes information on abortions per 1000 live births and the number of out-of-state abortions. This lets us visualize an important social factor that might motivate people to migrate in or out of their state of residence.</p>
<p>The dataset “presidential_election_data,” from the Federal Election Commission, contains the share of Republican votes in each state per election in 2008, 2012, and 2020. This lets us visualize the political demographics in states, which might motivate interstate migration.</p>
<p>The dataset “state_economic_data,” from the Federal Reserve, contains information on median household income for each state in the years 2008, 2012, 2016, and 2020. This lets us see if there might be economic reasons for interstate migration, in correlation with the other datasets.</p>
<p>The dataset “political_culture_elazar” correlates each state with a culture tag, as theorized by Daniel Elazar in 1966. This will allow us to recognize patterns between state culture and the other variables of our analysis.</p>
<p>The other datasets combine the above variables of interest in different ways for the purpose of building a predictive model.</p>
</section>
<section id="visualizations" class="level2">
<h2 class="anchored" data-anchor-id="visualizations"><strong>VISUALIZATIONS</strong></h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-1-1.gif" class="img-fluid"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.gif" class="img-fluid"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.gif" class="img-fluid"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.gif" class="img-fluid"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.gif" class="img-fluid"></p>
</div>
</div>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods"><strong>METHODS</strong></h2>
<p>We gathered data from the US Census, the CDC, FEC, and the Federal Reserve to obtain our variables of interest. Because one of our variables, partisanship in the presidential election, was limited to election years, we decided to only use data from those years in our other variables as well.</p>
<p>Some datasets originally taken from these websites were very messy, and we had to do a fair amount of data wrangling prior to creating visualizations or interpreting our data. Our datasets were cleaned to include only columns of interest. Generally this included the year, state, explanatory value for our research question, and any related values which we were considering incorporating with our explanatory value (for example, we included both abortions_per_1000_women and abortions_per_1000_live_births in our abortion datatset, as well as data on the number of people who had not moved and total state population in our migration dataset, in case we we decided to us ratios).</p>
<p>All of the values in all of our datasets were converted to numeric form. We removed NA values in some instances, though we did leave some in, especially within the abortion dataset, as we didn’t want to lose other data on entire states when combining datasets later in the process. In the case of political culture, we simply created a new dataset using Daniel Elazar’s culture classifications for each state. As these classifications are constant, there is no year variable in this dataset.</p>
<p>Starting with one dataset for each explanatory and response variable, we used a series of left and full join functions to create one dataset which contained all of our variables of interest. The final columns in our all variables dataset were state, Republican share of the general election, year, political culture, abortions per 1000 women, abortions per 1000 live births, the number of out of state abortions, median household income, total state population, number of people who had not moved states in one year, number of people who had moved states in one year, and the number of people who had not moved for every one person who had.</p>
<p>We used this dataset to create and interpret our logarithmic model, which allowed the coefficient estimates to be better interpreted than a linear model. We chose to use spatial-temporal visualizations for each of the individual variables listed above, using their respective datasets, in order to get a broad idea of how each factor changed over time and by state. A spatial visualization of the US (using the “maps” package) was decided to be the most intuitive option, and shading of each state by the socioeconomic factor in question provided a clear picture of each factor’s variance to between states.</p>
<p>We chose to animate by year rather than facet wrap, as we thought faceting would be too overwhelming to look at. Our shiny app was created to include a visualization of the US with options to select for each socioeconomic factor and year.</p>
</section>
<section id="interpretation-of-models" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-of-models"><strong>INTERPRETATION OF MODELS</strong></h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 7
  term                    estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;                      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept                  7.40      2.33      3.18    0.002    2.78    12.0  
2 log(`Median Household …   -0.367     0.213    -1.72    0.088   -0.79     0.056
3 log(Abortions_per_1000…    0.033     0.055     0.594   0.554   -0.077    0.142
4 log(`R Share of Genera…   -0.28      0.207    -1.36    0.178   -0.691    0.13 </code></pre>
</div>
</div>
<p>The intercept is 7.398, which indicates that in a state with a log Median household income of $0, log 0 abortions per 1000 women, and a 0 percent Republican share of the general election, the expected percentage of the population that comes from a different state is 7.398.</p>
<p>The log estimates are telling as well, for a increase of 1 in log of median household income, there is an associated increase of -0.367 in the number of people from different states entering the state compared to the population in the state at the time, holding all other variables constant.</p>
<p>For log of abortions per 1000 women, the estimate is a minimal change, with a p-value of 0.554, leading us to have little faith in the estimate. The Republican share of the general election has a similar impact to the median household income, but is slightly less pronounced. The p-value for log of Median Household Income is closest to 0.05, meaning that our trust in that prediction is the highest.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  term                    estimate std_error statistic p_value lower_ci upper_ci
  &lt;chr&gt;                      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 intercept                  40.9       2.39    17.1     0         36.2    45.6 
2 political_culture: Mor…    -5.44      3.38    -1.61    0.111    -12.1     1.27
3 political_culture: Tra…    -3.15      3.49    -0.903   0.369    -10.1     3.78</code></pre>
</div>
</div>
<p>This model was constructed because the other model was unable to account for categorical variables. It is possible that some sort of dummy variable system could be constructed to include the variables in the logarithmic model, but that was not the method we settled on.</p>
<p>The model uses a baseline of individualistic culture. From this baseline we can observe the two conditions. The differences from the baseline are telling, the moralistic cultures have the lowest predicted rate of people from different states moving in, while the traditionalistic states are very similar. Individualistic states are far and above the other two, and has a p-value that leads us to trust the result more than for the other two.</p>
</section>
<section id="interactive-dashboard" class="level2">
<h2 class="anchored" data-anchor-id="interactive-dashboard"><strong>INTERACTIVE DASHBOARD</strong></h2>
<p>The dashboard can be accessed by running it in RStudio. A screenshot is pictured below. It can also be accessed by clicking this link: <a href="https://jamesono.shinyapps.io/project-02-t1w/" class="uri">https://jamesono.shinyapps.io/project-02-t1w/</a></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion"><strong>CONCLUSION</strong></h2>
<p>We successfully gathered data from online sources regarding various cultural, political, and social factors and used it to create multiple spatial-temporal visualizations illustrating the variation in the selected factors between states, with the goal of identifying patterns in state-to-state migration. We used this data to create spatial temporal visualizations of these socioeconomic factors, a logarithmic model, and a shiny app. We found that political culture played a significant role in people’s decisions to move between states, namely the moralistic culture. Additionally, the log of median household income had a significant negative effect on interstate migration. These findings are consistent with our initial expectations, although the findings are not without their limitations.</p>
<p>Access to more granular demographic data could have been helpful, as it would have allowed for us to determine explanatory effects, as a result of these factors, on interstate migration. Things such as the race or income of the people moving could play a significant role in why people choose to move. There are likely patterns surrounding these demographic variables that range year to year. However, this was a limitation of our research, as the datasets we found did not contain data at that level of specificity for state-to-state migration. Some of the sample sizes were so small that data being free from demographic information meant that individual identities could not be ascertained. The data included numbers of people going from one state to another so specifically that sometimes the numbers were low enough that it could have posed an issue were demographic information included in the data.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>